---
ID: "var00005-0001-0001-0001-000000000003"
Parent: "var00005-0001-0001-0001-000000000002"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/templates/Branches/Project/kit-next-realstate/Sitecore Properties/Variants/CommunityShowcase Headless Variants/CommunityShowcase/Default"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251207T000000Z
