# Placeholder for ProductListing Headless Variants (to be customized for Sitecore Properties)
---
ID: "{A8B9C0D1-E2F3-45A6-7B8C-9D0E1F2A3B4C}"
Name: "ProductListing Headless Variants"
Parent: "{E5F6A7B8-C9D0-41E2-3F4A-5B6C7D8E9F0A}"
Template: "{28282828-2828-2828-2828-282828282828}"
Path: "/sitecore/templates/Branches/Project/sitecore-properties.templates.branches/Sitecore Properties/Variants/ProductListing Headless Variants"
Description: "Product listing variants for Sitecore Properties."
Fields:
	- "ProductListingVariant"
Languages:
	- Language: en
		Versions:
			- Version: 1
				Fields:
					- ID: "{29292929-2929-2929-2929-292929292929}"
						Hint: __Created
						Value: 20251210T000000Z
